apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '1'
  labels:
    app.kubernetes.io/name: event-streams-topic
  name: event-streams-topic
  namespace: event-streams-topic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-streams-topic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: event-streams-topic
    spec:
      containers:
      - args:
        - -logtostderr=true
        - -v=5
        command:
        - ./manager
        image: cloudoperators/event-streams-topic:0.1.0
        imagePullPolicy: Always
        name: topic
      serviceAccountName: event-streams-topic
